# 应用名称
spring:
  application:
    name: millionDataExport
# 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
# 数据源名称
    name: defaultDataSource
# 数据库连接地址
    url: jdbc:mysql://localhost:3306/data_export?characterEncoding=utf-8&serverTimezone=Asia/Shanghai

# 数据库用户名&密码：
    username: root
    password: 333
# 应用服务 WEB 访问端口
server:
  port: 8080
#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
#指定Mybatis的实体目录
  type-aliases-package: com.chen.milliondataexport.export.mapper


